name: login_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Cliente API REST
  http: ^1.2.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:

  # Tests de integración

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true